#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# THIS IS JUST A DEMO! USE YOUR OWN (see /boot/grub2/grub.conf)
# make sure to use 'vmlinuz' and 'initrd' WITHOUT kernel version numbers as below
# don't forget to add the kernel paramter 'start_rescue_ssh'
#
# Run 'grub2-mkconfig > /boot/grub2/grub.cfg' or 'yast2 bootloader' after changes to '/etc/grub.d/'.
#

menuentry 'Rescue SSH' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_msdos 
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 --hint='hd0,msdos1' XXXXXX-XXXX-XXXX...
	else
	  search --no-floppy --fs-uuid --set=root XXXXXX-XXXX-XXXX...
	fi
	echo	'Loading Linux ...'
	linux	/vmlinuz root=UUID=YYYYYY-YYYY-YYYY... splash=silent quiet showopts start_rescue_ssh
	echo	'Loading initial ramdisk ...'
	initrd	/initrd
}
